plugins {
    id 'com.android.application'
}

android {
    namespace 'com.personal.shiftcalendaralarm'
    compileSdk 35

    defaultConfig {
        applicationId 'com.personal.shiftcalendaralarm'
        minSdk 26
        targetSdk 35
        versionCode 13
        versionName '0.13-main-ui-color-snooze'
    }
}
