plugins {
    id 'com.android.application'
}

android {
    namespace 'com.personal.shiftcalendaralarm'
    compileSdk 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'com.personal.shiftcalendaralarm'
        minSdk 26
        targetSdk 35
        versionCode 30
        versionName '0.30-alarm-auto-stop'
    }
}
